---
title: "In-Class Exercise 4"
author: "Loh Jiahui"
date: "6 May 2023"
date-modified: "`r Sys.Date()`"
execute: 
  echo: true
  eval: true
  warning: false
---

## 1 Loading R packages and data

```{r}
pacman::p_load(rstatix, gt, patchwork, tidyverse)
```

```{r}
exam_data <- read_csv("data/Exam_data.csv")
```

## 2 Visualising Normal Distribution 

::: panel-tabset

## The plot
```{r}
#| echo: false
#| fig-width: 4
#| fig-height: 4

ggplot(exam_data,
       aes(sample=ENGLISH)) +
  stat_qq() +
  stat_qq_line() 
```

## The Code Chunk
```{r}
#| eval: false
#| fig-width: 4
#| fig-height: 4

ggplot(exam_data,
       aes(sample=ENGLISH)) + #aes not taking value of x,y
  stat_qq() + #calculate if sample is normal 
  stat_qq_line() #plot the theoretical line
```
:::

::: callout-note
We can see that the points deviate significantly from the straight diagonal line. This is a clear indication that the set of data is not normally distributed. 
:::

## Combining Statistical Graph

::: panel-tabset

## The plot
```{r}
#| echo: false

qq <- ggplot(exam_data,
       aes(sample=ENGLISH)) +
  stat_qq() +
  stat_qq_line() 

sw_t <- exam_data %>%
  shapiro_test(ENGLISH) %>%
  gt()

tmp <- tempfile(fileext = '.png')
gtsave(sw_t, tmp) #save sw_t into temp folder
table_png <- png::readPNG(tmp, native = TRUE)

qq + table_png
```

## The Code Chunk
```{r}
#| eval: false

qq <- ggplot(exam_data,
       aes(sample=ENGLISH)) +
  stat_qq() +
  stat_qq_line() 

sw_t <- exam_data %>%
  shapiro_test(ENGLISH) %>%
  gt()

tmp <- tempfile(fileext = '.png')
gtsave(sw_t, tmp) #save sw_t into temp folder
table_png <- png::readPNG(tmp,
                          native = TRUE)

qq + table_png
```
:::

